/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wallet_JniUtils */

#ifndef _Included_com_wallet_JniUtils
#define _Included_com_wallet_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wallet_JniUtils
 * Method:    getbbCourseKeyFromC
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
#include "com_wallet_JniUtils.h"

JNIEXPORT void JNICALL Java_com_wallet_JniUtils_getbbCourseKeyFromC
        (JNIEnv *env,jclass clz, jobject contextObject);

#ifdef __cplusplus
}
#endif
#endif
