/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wallet_utils_JniUtils */

#ifndef _Included_com_wallet_utils_JniUtils
#define _Included_com_wallet_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wallet_utils_JniUtils
 * Method:    getbbCourseKeyFromC
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wallet_utils_JniUtils_getbbCourseKeyFromC
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
